### ISSUE TITLE
builds the same container thrice

### ISSUE THREAD

**Issue by wideglide** [singularityhub/singularity-deploy#1]
https://github.com/singularityhub/singularity-deploy/blob/ca4ba3daf22059cb5fb020b90e9397b415fa433b/.github/workflows/builder.yml#L59

This should be: 
```
singularity build --fakeroot container.sif $recipe
```

**Comment by vsoch** [comment]
Good catch! Would you like to open a PR to fix?

**Comment by vsoch** [comment]
If not, I can quickly make the fix at the end of the day.
