### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by q-posev** [singularityhub/singularity-deploy#10]
For some use cases, one may want to re-use the Github CI workflows (`.yml`) without actually forking the repository. For example, to enable the Singularity container deployment within the existing Github repo. I am not sure that this is possible at the moment due to the absence of a permissive license. Could you please add one?

**Comment by vsoch** [comment]
All set https://github.com/singularityhub/singularity-deploy/commit/7eefd626ffe74c28c0a93a212f0516569f0536fb. Thanks!
